In [1]:
import numpy as np
import pandas as pd
from cvxopt import matrix, solvers
from scipy.optimize import minimize

## Question-1

In [2]:
def f(x):
    x0=x[0]
    x1=x[1]
    x2=x[2]
    x3=x[3]
    return (-x0 - x1 - x2 - x3)

def c1(x):
    x0=x[0]
    x1=x[1]
    x2=x[2]
    x3=x[3]
    return (x0-x1)**2 + (x2 + 2*x3)**4 - 5

def c2(x):
    x0=x[0]
    x1=x[1]
    x2=x[2]
    x3=x[3]
    return x0+2*x1+3*x2+4*x3-6

cons = ({'type': 'ineq', 'fun': c1}, {'type': 'ineq', 'fun': c2})
bounds = [(0, None), (0, None), (0, None), (0, None)]
x0 = np.zeros(4)

result = minimize(f, x0, method='SLSQP', bounds=bounds, constraints=cons)

print("Optimal solution:")
print("x1 =", np.round(result.x[0], decimals = 3))
print("x2 =", np.round(result.x[1], decimals = 3))
print("x3 =", np.round(result.x[2], decimals = 3))
print("x4 =", np.round(result.x[3], decimals = 3))

Optimal solution:
x1 = 2.8497099366136913e+31
x2 = 2.8497099366136895e+31
x3 = 3.5890973769734204e+31
x4 = 4.328484790104133e+31


## Question-2

In [3]:
data = pd.read_excel('2_col_revised.xlsx')
data=data.values
x=data[:,0].reshape(-1,1)
y=data[:,-1]
n = len(x)
x[n-1]= 4
R = 4
degrees = [1, 2, 3, 4, 5, 6, 7]
r = 14
def f(x0):
    return np.sum(x0)

def constraint(x0, power):
    fitted_values = np.sum(x0 * (x**power)) - y
    return np.sum(fitted_values)

print("Price of 5-thousand square feet house:-")
for degree in degrees:
    initial_guess = np.ones(degree + 1)
    poly_constraint = {'type': 'eq', 'fun': lambda alpha: constraint(alpha, degree)}

    bounds = [(0, None) for _ in range(degree + 1)]
    result = minimize(f, initial_guess, method='SLSQP', constraints=[poly_constraint], bounds=bounds)

    if result.success and result.fun <= r:
        price = np.polyval(result.x, R)*100
        print(f"For degree: {degree}, Price: {price:.2f}")

FileNotFoundError: [Errno 2] No such file or directory: '2_col_revised.xlsx'

## Question-3

considering x2 = x3 - x4 s.t x3>=0, x4>=0

min 3*x1 − 4*x3 + 4*x4

In [19]:
A = np.array([[1, 3, -3], [2, -1, 1], [-1, 4, -4], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
b = np.array([[12], [20], [-5], [0], [0], [0]])
c = np.array([[3], [-4], [4]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a1 = np.round(soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Minimum value is",a1)

     pcost       dcost       gap    pres   dres   k/t
 0:  2.2229e+01 -2.8329e+01  4e+01  1e-01  3e+00  1e+00
 1:  1.8978e+01  5.8559e+00  1e+01  4e-02  7e-01  5e-01
 2:  5.8896e+00  2.4793e+00  6e+00  1e-02  2e-01  6e-01
 3:  5.0172e+00  4.9655e+00  9e-02  2e-04  3e-03  8e-03
 4:  5.0002e+00  4.9997e+00  9e-04  2e-06  3e-05  8e-05
 5:  5.0000e+00  5.0000e+00  9e-06  2e-08  3e-07  8e-07
 6:  5.0000e+00  5.0000e+00  9e-08  2e-10  3e-09  8e-09
Optimal solution found.
[[-0.     ]
 [ 3.05765]
 [ 4.30765]]
Minimum value is 5.0


dual of the problem

max -12*y1 - 20*y2 + 5*y3

In [22]:
A = np.array([[-1, -2, 1], [-3, 1, -4], [3, -1, 4], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
b = np.array([[3], [-4], [4], [0], [0], [0]])
c = np.array([[12], [20], [-5]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a2 = np.round(-soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Maximum value is", a2)

     pcost       dcost       gap    pres   dres   k/t
 0: -2.2229e+01 -2.6445e+01  4e+01  7e-01  2e-01  1e+00
 1: -1.9235e+01 -2.0094e+01  1e+01  2e-01  6e-02  5e-01
 2: -6.4514e+00 -6.2208e+00  6e+00  6e-02  2e-02  6e-01
 3: -5.0242e+00 -5.0221e+00  9e-02  8e-04  2e-04  8e-03
 4: -5.0002e+00 -5.0002e+00  9e-04  8e-06  2e-06  8e-05
 5: -5.0000e+00 -5.0000e+00  9e-06  8e-08  2e-08  8e-07
 6: -5.0000e+00 -5.0000e+00  9e-08  8e-10  2e-10  8e-09
Optimal solution found.
[[-0.]
 [-0.]
 [ 1.]]
Maximum value is 5.0


duality gap

In [23]:
duality_gap = (a1 - a2)
print(duality_gap)

0.0


## Question-4

min (R + 3)x1 + (R + 41)x2

In [28]:
A = np.array([[3, -1], [7, 11], [-1, 0], [0, -1]])
b = np.array([[12], [88], [0], [0]])
c = np.array([[17], [55]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a1 = np.round(soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Minimum value is",a1)

     pcost       dcost       gap    pres   dres   k/t
 0:  3.4209e+02 -2.0732e+02  6e+01  0e+00  1e+00  1e+00
 1:  5.1115e+01 -2.3905e+03  2e+03  1e-15  5e+00  4e+01
 2:  2.4673e+01 -1.8843e+02  2e+02  2e-16  5e-01  5e+00
 3:  1.4274e+00 -3.9645e+00  5e+00  2e-16  1e-02  8e-01
 4:  1.4462e-02 -3.9947e-02  5e-02  2e-16  1e-04  8e-03
 5:  1.4463e-04 -3.9949e-04  5e-04  4e-16  1e-06  8e-05
 6:  1.4463e-06 -3.9949e-06  5e-06  2e-16  1e-08  8e-07
 7:  1.4463e-08 -3.9949e-08  5e-08  4e-16  1e-10  8e-09
Optimal solution found.
[[0.]
 [0.]]
Minimum value is 0.0


dual of the problem

In [29]:
A = np.array([[-3, -7], [1, -11], [-1, 0], [0, -1]])
b = np.array([[17], [55], [0], [0]])
c = np.array([[12], [88]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a2 = np.round(-soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Maximum value is", a2)

     pcost       dcost       gap    pres   dres   k/t
 0: -3.4209e+02 -3.4209e+02  6e+01  2e-01  0e+00  1e+00
 1: -8.5892e+01 -5.1115e+01  2e+03  9e-01  6e-15  4e+01
 2: -2.9271e+01 -2.4673e+01  2e+02  8e-02  6e-16  5e+00
 3: -2.2326e+00 -1.4274e+00  5e+00  2e-03  2e-16  8e-01
 4: -2.2630e-02 -1.4462e-02  5e-02  2e-05  4e-17  8e-03
 5: -2.2631e-04 -1.4463e-04  5e-04  2e-07  2e-16  8e-05
 6: -2.2631e-06 -1.4463e-06  5e-06  2e-09  4e-16  8e-07
 7: -2.2631e-08 -1.4463e-08  5e-08  2e-11  0e+00  8e-09
Optimal solution found.
[[ 0.]
 [-0.]]
Maximum value is 0.0


Duality gap

In [30]:
duality_gap = (a1 - a2)
print(duality_gap)

0.0


## Question-5

min Rx1 − (R − 1)x2

In [33]:
A = np.array([[3, -2], [3, -2], [-1, 0], [0, -1]])
b = np.array([[1], [6], [0], [0]])
c = np.array([[14], [-13]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))

     pcost       dcost       gap    pres   dres   k/t
 0:  1.7630e+01 -9.8519e+00  2e+01  1e+00  1e+00  1e+00
 1: -6.4135e+02 -1.1288e+03  6e+04  3e+01  3e+01  2e+02
 2: -3.7899e+01 -2.7281e+00  5e+01  1e+00  1e+00  6e+01
 3: -6.7454e+03 -3.4414e+01  2e+04  2e+00  3e+00  7e+03
 4: -6.8033e+05 -3.4663e+01  2e+06  2e+00  3e+00  7e+05
 5: -6.8040e+07 -3.4663e+01  2e+08  2e+00  3e+00  7e+07
Certificate of dual infeasibility found.


dual of the problem

In [34]:
A = np.array([[3, 3], [-2, -2], [-1, 0], [0, -1]])
b = np.array([[14], [-13], [0], [0]])
c = np.array([[-1], [-6]])
soln=solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))

     pcost       dcost       gap    pres   dres   k/t
 0: -1.7630e+01 -2.1259e+01  6e+01  4e-01  3e-16  1e+00
 1:  2.4738e+01  2.4586e+01  4e+02  7e-01  1e-14  7e+00
 2: -3.6832e+01  6.0238e+01  1e+03  5e-01  9e-14  1e+02
 3: -2.9334e+01  9.2510e+03  2e+05  6e-01  1e-11  9e+03
 4: -2.9333e+01  9.2835e+05  2e+07  6e-01  9e-11  9e+05
 5: -2.9333e+01  9.2838e+07  2e+09  6e-01  9e-09  9e+07
Certificate of primal infeasibility found.


## Question-6

max z = x1 + x2 + x3

In [35]:
A = np.array([[3, 2, 1], [2, 1, 2], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
b = np.array([[3], [2], [0], [0], [0]])
c = np.array([[-1], [-1], [-1]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a1 = np.round(-soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Maximum value is",a1)

     pcost       dcost       gap    pres   dres   k/t
 0: -1.2000e+00 -7.7000e+00  9e+00  6e-01  4e+00  1e+00
 1: -1.4061e+00 -2.5268e+00  7e-01  1e-01  7e-01  2e-01
 2: -1.6525e+00 -1.7345e+00  5e-02  7e-03  4e-02  3e-03
 3: -1.6665e+00 -1.6674e+00  6e-04  8e-05  5e-04  4e-05
 4: -1.6667e+00 -1.6667e+00  6e-06  8e-07  5e-06  4e-07
 5: -1.6667e+00 -1.6667e+00  6e-08  8e-09  5e-08  4e-09
Optimal solution found.
[[0.      ]
 [1.333333]
 [0.333333]]
Maximum value is 1.66667


dual of the problem

In [36]:
A = np.array([[-3, -2], [-2, -1], [-1, -2], [-1, 0], [0, -1]])
b = np.array([[-1], [-1], [-1], [0], [0]])
c = np.array([[3], [2]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a2 = np.round(soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Minimum value is", a2)

     pcost       dcost       gap    pres   dres   k/t
 0:  1.2000e+00  4.2000e+00  9e+00  2e+00  3e+00  1e+00
 1:  1.3661e+00  1.9418e+00  7e-01  3e-01  5e-01  2e-01
 2:  1.6611e+00  1.6864e+00  5e-02  2e-02  3e-02  3e-03
 3:  1.6666e+00  1.6669e+00  6e-04  2e-04  3e-04  4e-05
 4:  1.6667e+00  1.6667e+00  6e-06  2e-06  3e-06  4e-07
 5:  1.6667e+00  1.6667e+00  6e-08  2e-08  3e-08  4e-09
Optimal solution found.
[[0.333333]
 [0.333333]]
Minimum value is 1.66667


duality gap

In [38]:
duality_gap = (a1 - a2)
print(duality_gap)

0.0


## Question-7

max z = 16x1 + 17x2

In [40]:
A = np.array([[2, 1], [1, 1], [2, 4], [-1, 0], [0, -1]])
b = np.array([[1000], [600], [2000], [0], [0]])
c = np.array([[-16], [-17]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a1 = np.round(-soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Maximum value is",a1)

     pcost       dcost       gap    pres   dres   k/t
 0: -1.0357e+04 -2.0061e+04  3e+03  3e-02  7e-01  1e+00
 1: -9.5663e+03 -1.6482e+04  2e+03  2e-02  5e-01  2e+02
 2: -9.9583e+03 -1.0252e+04  8e+01  8e-04  2e-02  7e+00
 3: -9.9995e+03 -1.0005e+04  1e+00  2e-05  5e-04  2e-01
 4: -1.0000e+04 -1.0000e+04  1e-02  2e-07  5e-06  2e-03
 5: -1.0000e+04 -1.0000e+04  1e-04  2e-09  5e-08  2e-05
Optimal solution found.
[[200.000027]
 [399.999972]]
Maximum value is 9999.99995


dual of the problem

min 1000*y1 + 600*y2 + 2000*y3

In [42]:
A = np.array([[-2, -1, -2], [-1, -1, -4], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
b = np.array([[-16], [-17], [0], [0], [0]])
c = np.array([[1000], [600], [2000]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a2= np.round(soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Minimum value is", a2)

     pcost       dcost       gap    pres   dres   k/t
 0:  1.0357e+04  1.1250e+04  3e+03  3e-01  1e-01  1e+00
 1:  9.4061e+03  1.0218e+04  2e+03  2e-01  7e-02  2e+02
 2:  9.9509e+03  9.9861e+03  8e+01  8e-03  3e-03  7e+00
 3:  9.9993e+03  1.0000e+04  1e+00  2e-04  6e-05  2e-01
 4:  1.0000e+04  1.0000e+04  1e-02  2e-06  6e-07  2e-03
 5:  1.0000e+04  1.0000e+04  1e-04  2e-08  6e-09  2e-05
Optimal solution found.
[[-0. ]
 [15. ]
 [ 0.5]]
Minimum value is 9999.99993


duality gap

In [44]:
duality_gap = np.round((a1 - a2), decimals = 3)
print(duality_gap)

0.0


## Question-8

min 2x1 + 3x2 + 10x3

In [45]:
A = np.array([[1, 0, 2], [-1, 0, -2], [0, -1, -1], [0, 1, 1], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
b = np.array([[0], [0], [-1], [1], [0], [0], [0]])
c = np.array([[2], [3], [10]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a1 = np.round(soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Minimum value is",a1)

     pcost       dcost       gap    pres   dres   k/t
 0:  2.8205e+00  2.8205e+00  2e+01  2e+00  4e-01  1e+00
 1:  2.6616e+00  2.6828e+00  2e+00  2e-01  4e-02  1e-01
 2:  2.9966e+00  2.9982e+00  2e-02  3e-03  5e-04  3e-03
 3:  3.0000e+00  3.0000e+00  2e-04  3e-05  5e-06  3e-05
 4:  3.0000e+00  3.0000e+00  2e-06  3e-07  5e-08  3e-07
 5:  3.0000e+00  3.0000e+00  2e-08  3e-09  5e-10  3e-09
Optimal solution found.
[[ 0.]
 [ 1.]
 [-0.]]
Minimum value is 3.0


dual of the problem

max y3 - y4

In [46]:
A = np.array([[1, -1, 0, 0], [0, 0, 1, -1], [2, -2, 1, -1], [-1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
b = np.array([[2], [3], [10], [0], [0], [0], [0]])
c = np.array([[0], [0], [-1], [1]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a2 = np.round(-soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Maximum value is", a2)

     pcost       dcost       gap    pres   dres   k/t
 0: -2.8205e+00 -2.2051e+01  2e+01  6e-01  5e+00  1e+00
 1: -2.6828e+00 -4.5938e+00  2e+00  6e-02  5e-01  1e-01
 2: -2.9982e+00 -3.0227e+00  2e-02  8e-04  7e-03  3e-03
 3: -3.0000e+00 -3.0002e+00  2e-04  8e-06  7e-05  3e-05
 4: -3.0000e+00 -3.0000e+00  2e-06  8e-08  7e-07  3e-07
 5: -3.0000e+00 -3.0000e+00  2e-08  8e-10  7e-09  3e-09
Optimal solution found.
[[2.50097 ]
 [1.107017]
 [3.807784]
 [0.807784]]
Maximum value is 3.0


duality gap

In [48]:
duality_gap = np.round((a1 - a2), decimals = 6)
print(duality_gap)

0.0


## Question-9

considering x2 = x3 - x4 s.t x3>=0, x4>=0

min 3*x1 − 4*x3 + 4*x4

In [49]:
A = np.array([[1, 3, -3], [2, -1, 1], [-1, 4, -4], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
b = np.array([[12], [20], [-5], [0], [0], [0]])
c = np.array([[3], [-4], [4]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a1 = np.round(soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Minimum value is",a1)

     pcost       dcost       gap    pres   dres   k/t
 0:  2.2229e+01 -2.8329e+01  4e+01  1e-01  3e+00  1e+00
 1:  1.8978e+01  5.8559e+00  1e+01  4e-02  7e-01  5e-01
 2:  5.8896e+00  2.4793e+00  6e+00  1e-02  2e-01  6e-01
 3:  5.0172e+00  4.9655e+00  9e-02  2e-04  3e-03  8e-03
 4:  5.0002e+00  4.9997e+00  9e-04  2e-06  3e-05  8e-05
 5:  5.0000e+00  5.0000e+00  9e-06  2e-08  3e-07  8e-07
 6:  5.0000e+00  5.0000e+00  9e-08  2e-10  3e-09  8e-09
Optimal solution found.
[[-0.      ]
 [ 3.057647]
 [ 4.307647]]
Minimum value is 5.0


dual of the problem

max -12*y1 - 20*y2 + 5*y3

In [51]:
A = np.array([[-1, -2, 1], [-3, 1, -4], [3, -1, 4], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
b = np.array([[3], [-4], [4], [0], [0], [0]])
c = np.array([[12], [20], [-5]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a2 = np.round(-soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Maximum value is", a2)

     pcost       dcost       gap    pres   dres   k/t
 0: -2.2229e+01 -2.6445e+01  4e+01  7e-01  2e-01  1e+00
 1: -1.9235e+01 -2.0094e+01  1e+01  2e-01  6e-02  5e-01
 2: -6.4514e+00 -6.2208e+00  6e+00  6e-02  2e-02  6e-01
 3: -5.0242e+00 -5.0221e+00  9e-02  8e-04  2e-04  8e-03
 4: -5.0002e+00 -5.0002e+00  9e-04  8e-06  2e-06  8e-05
 5: -5.0000e+00 -5.0000e+00  9e-06  8e-08  2e-08  8e-07
 6: -5.0000e+00 -5.0000e+00  9e-08  8e-10  2e-10  8e-09
Optimal solution found.
[[-0.]
 [-0.]
 [ 1.]]
Maximum value is 5.0


duality gap

In [52]:
duality_gap = np.round((a1 - a2), decimals = 6)
print(duality_gap)

0.0


## Question-10

max 14x1 + 17x2

In [53]:
A = np.array([[-3, -1], [-1, -4], [1, 1], [-1, 0], [0, -1]])
b = np.array([[-3], [-4], [5], [0], [0]])
c = np.array([[-14], [-17]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a1 = np.round(-soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Maximum value is",a1)

     pcost       dcost       gap    pres   dres   k/t
 0: -2.7732e+01 -1.9659e+01  2e+01  0e+00  1e+00  1e+00
 1: -7.5642e+01 -5.9363e+01  1e+02  5e-16  2e+00  5e+00
 2: -7.8140e+01 -7.6849e+01  9e+00  3e-16  1e-01  5e-01
 3: -8.4785e+01 -8.4367e+01  3e+00  8e-16  4e-02  2e-01
 4: -8.4859e+01 -8.4794e+01  3e-01  3e-16  4e-03  4e-02
 5: -8.4999e+01 -8.4998e+01  3e-03  5e-16  4e-05  4e-04
 6: -8.5000e+01 -8.5000e+01  3e-05  3e-16  4e-07  4e-06
 7: -8.5000e+01 -8.5000e+01  3e-07  1e-16  4e-09  4e-08
Optimal solution found.
[[0.]
 [5.]]
Maximum value is 85.0


dual of the problem

min -3*y1 - 4*y2 + 5*y3

In [54]:
A = np.array([[3, 1, -1], [1, 4, -1], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
b = np.array([[-14], [-17], [0], [0], [0]])
c = np.array([[-3], [-4], [5]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a2 = np.round(soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Minimum value is", a2)

     pcost       dcost       gap    pres   dres   k/t
 0:  2.7732e+01  2.7732e+01  2e+01  4e-01  3e-16  1e+00
 1:  7.1794e+01  7.5642e+01  1e+02  6e-01  1e-15  5e+00
 2:  7.7776e+01  7.8140e+01  9e+00  5e-02  6e-16  5e-01
 3:  8.4614e+01  8.4785e+01  3e+00  1e-02  2e-15  2e-01
 4:  8.4821e+01  8.4859e+01  3e-01  1e-03  3e-15  4e-02
 5:  8.4998e+01  8.4999e+01  3e-03  1e-05  1e-15  4e-04
 6:  8.5000e+01  8.5000e+01  3e-05  1e-07  1e-15  4e-06
 7:  8.5000e+01  8.5000e+01  3e-07  1e-09  3e-15  4e-08
Optimal solution found.
[[-0.]
 [-0.]
 [17.]]
Minimum value is 85.0


duality gap

In [55]:
duality_gap = np.round((a1 - a2), decimals = 6)
print(duality_gap)

0.0


## Question-11

min 14x1 + 29x2

In [56]:
A = np.array([[2, 1], [-3, -4], [-2, 3], [-1, 0], [0, -1]])
b = np.array([[4], [-24], [-6], [0], [0]])
c = np.array([[14], [29]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))

     pcost       dcost       gap    pres   dres   k/t
 0:  1.1150e+02  1.9529e+02  1e+02  7e-01  4e-01  1e+00
 1:  1.6013e+02  6.1752e+02  5e+03  3e+00  2e+00  4e+01
 2:  6.2859e+03  3.0388e+04  2e+07  1e+02  8e+01  7e+03
 3:  7.9914e+01  6.2671e+02  2e+03  1e+00  6e-01  4e+02
 4:  8.7620e+01  3.7872e+04  2e+05  1e+00  7e-01  4e+04
 5:  8.7631e+01  3.7655e+06  2e+07  1e+00  7e-01  4e+06
 6:  8.7631e+01  3.7652e+08  2e+09  1e+00  7e-01  4e+08
Certificate of primal infeasibility found.


dual of the problem

max -4*y1 + 24*y2 + 6*y3

In [57]:
A = np.array([[-2, 3, 2], [-1, 4, -3], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
b = np.array([[14], [29], [0], [0], [0]])
c = np.array([[4], [-24], [-6]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))

     pcost       dcost       gap    pres   dres   k/t
 0: -1.1150e+02 -4.3043e+02  1e+02  2e-01  2e+00  1e+00
 1: -1.9754e+02 -1.7587e+03  5e+03  1e+00  1e+01  4e+01
 2: -1.3140e+04 -7.1937e+04  2e+07  5e+01  5e+02  7e+03
 3: -5.0571e+02 -5.4047e+02  2e+03  3e-01  3e+00  4e+02
 4: -3.7739e+04 -5.9300e+02  2e+05  4e-01  4e+00  4e+04
 5: -3.7653e+06 -5.9309e+02  2e+07  4e-01  4e+00  4e+06
 6: -3.7652e+08 -5.9309e+02  2e+09  4e-01  4e+00  4e+08
Certificate of dual infeasibility found.


## Question-12

min 18x1 + x2

In [58]:
A = np.array([[1, 2], [-4, -3], [3, 1], [-3, -1], [-1, 0], [0, -1]])
b = np.array([[3], [-6], [3], [-3], [0], [0]])
c = np.array([[17], [1]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a1 = np.round(soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Minimum value is",a1)

     pcost       dcost       gap    pres   dres   k/t
 0:  1.2614e+01  2.3318e+01  3e+01  4e-01  9e-01  1e+00
 1:  1.0726e+01  1.1724e+01  1e+00  3e-02  7e-02  3e-01
 2:  1.1393e+01  1.1405e+01  2e-02  3e-04  8e-04  4e-03
 3:  1.1400e+01  1.1400e+01  2e-04  3e-06  8e-06  4e-05
 4:  1.1400e+01  1.1400e+01  2e-06  3e-08  8e-08  4e-07
Optimal solution found.
[[0.6]
 [1.2]]
Minimum value is 11.4


dual of the problem

max -3*y1 + 6*y2 + 3*y3 - 3*y4

In [59]:
A = np.array([[-1, 4, 3, -3], [-2, 3, 1, -1], [-1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
b = np.array([[17], [1], [0], [0], [0], [0]])
c = np.array([[3], [-6], [-3], [3]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))
a2 = np.round(-soln['primal objective'], decimals=5)
print(np.round_(soln['x'],decimals=6))
print("Maximum value is", a2)

     pcost       dcost       gap    pres   dres   k/t
 0: -1.2614e+01 -3.4295e+01  3e+01  5e-01  1e+00  1e+00
 1: -1.0943e+01 -1.2309e+01  1e+00  4e-02  1e-01  3e-01
 2: -1.1396e+01 -1.1412e+01  2e-02  5e-04  1e-03  4e-03
 3: -1.1400e+01 -1.1400e+01  2e-04  5e-06  1e-05  4e-05
 4: -1.1400e+01 -1.1400e+01  2e-06  5e-08  1e-07  4e-07
 5: -1.1400e+01 -1.1400e+01  2e-08  5e-10  1e-09  4e-09
Optimal solution found.
[[4.990061]
 [2.190061]
 [5.007773]
 [0.597834]]
Maximum value is 11.4


duality gap

In [60]:
duality_gap = np.round((a1 - a2), decimals = 6)
print(duality_gap)

0.0


## Question-13

min -3x1 + x2

In [61]:
A = np.array([[1, 2], [-1, -2], [2, -2], [-2, 2], [-1, 0], [0, -1]])
b = np.array([[0], [0], [9], [-9], [0], [0]])
c = np.array([[-3], [1]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))

     pcost       dcost       gap    pres   dres   k/t
 0: -9.6842e+00 -9.6842e+00  2e+01  5e-01  7e-01  1e+00
 1: -8.2442e+00 -5.7319e+00  7e+01  3e-01  5e-01  3e+00
 2: -8.7914e+00  2.9900e+02  8e+03  4e-01  6e-01  3e+02
 3: -8.7914e+00  3.0839e+04  8e+05  4e-01  6e-01  3e+04
 4: -8.7914e+00  3.0848e+06  8e+07  4e-01  6e-01  3e+06
 5: -8.7914e+00  3.0849e+08  8e+09  4e-01  6e-01  3e+08
Certificate of primal infeasibility found.


dual of the problem

max 9*y3 - 9*y4

In [62]:
A = np.array([[1, -1, 2, -2], [2, -2, -2, 2], [-1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
b = np.array([[-3], [1], [0], [0], [0], [0]])
c = np.array([[0], [0], [-9], [9]])
soln = solvers.lp(matrix(c,tc='d'),matrix(A,tc='d'),matrix(b,tc='d'))

     pcost       dcost       gap    pres   dres   k/t
 0:  9.6842e+00  1.4632e+01  2e+01  1e+00  9e-01  1e+00
 1:  5.7319e+00  1.1829e+01  7e+01  9e-01  7e-01  3e+00
 2: -2.9900e+02  1.2824e+01  8e+03  1e+00  7e-01  3e+02
 3: -3.0839e+04  1.2824e+01  8e+05  1e+00  7e-01  3e+04
 4: -3.0848e+06  1.2824e+01  8e+07  1e+00  7e-01  3e+06
 5: -3.0849e+08  1.2824e+01  8e+09  1e+00  7e-01  3e+08
Certificate of dual infeasibility found.
