Mruganshi Gohel

B20CS014

In [155]:
import numpy as np
from cvxopt import matrix, solvers
import random
from pandas.core.common import flatten

# Question -1

*Step -1: Function define*

In [156]:
def f(x):
    return (x[0] - 4)**2 + (x[1]- 4)**2

In [157]:
x0 = np.array([-0.5 * 4, 1.5 * 4])
f(x0)

40.0

*Step-2: Find Gredient and hessian of the given function*

In [158]:
def grad_hess_f(x):
  f0=f(x)
  n=len(x)
  h= 10**(-5)
  b=np.zeros(n)
  g=np.zeros(n)
  H=np.zeros((n,n))
  for i in range(0,n):
    x1=x.copy()
    x1[i]=x1[i]+h
    b[i]=f(x1)
    g[i]=(f(x1)-f0)/h
  for i in range(0,n):
    for j in range(0,n):
      x2=x.copy()
      x2[i]=x2[i]+h
      x2[j]=x2[j]+h
      H[i][j]=(f(x2)-b[i]-b[j]+f0)/h**2
  return g,H

In [159]:
g,h = grad_hess_f(x0)
print(g)
print(h)

[-11.99999   4.00001]
[[1.99982253 0.        ]
 [0.         1.99996464]]


*Step-3: Find Eigen values of hessian matrix*

In [160]:
np.linalg.eig(h)

(array([1.99982253, 1.99996464]),
 array([[1., 0.],
        [0., 1.]]))

***Eigen values are positive and hence it is positive definite and function is convex function***

*Step-5: if hessian matrix is positive definite then find optimal solution*

In [161]:
A=np.vstack((-np.identity(2),np.identity(2)))
lb=[-2*4,-2*4]
ub=[2*4,2*4]
b=np.append(x0-lb,ub-x0)

In [162]:
soln= solvers.qp(matrix(h),matrix(g),matrix(A),matrix(b))
print(np.round_(soln['x'],decimals=5),soln['primal objective'])
v1_11=np.round_(soln['x'],decimals=5)

     pcost       dcost       gap    pres   dres
 0: -3.2002e+01 -1.1201e+02  8e+01  5e-17  0e+00
 1: -3.9813e+01 -4.5444e+01  6e+00  4e-16  2e-16
 2: -4.0003e+01 -4.0075e+01  7e-02  1e-16  6e-17
 3: -4.0003e+01 -4.0004e+01  7e-04  1e-16  4e-17
 4: -4.0003e+01 -4.0003e+01  7e-06  1e-16  9e-17
Optimal solution found.
[[ 6.00053]
 [-2.00004]] -40.00322546304221


*Solution Correctness Check: if **dot product of gradient and optimal solution** is coming out **negative** then solution is correct (as said in the lab lecture by sir)*

In [163]:
v1_11=list(flatten(v1_11))
v2_11=list(g)
np.dot(v2_11,v1_11)

-80.0064799913572

# Question -2

*Step-1: function defining as per question and taking dimension as 10 in input*

In [164]:
import numpy as np

#function f1
def f1_1(x):
    n = len(x)
    I1 = [i for i in range(2, n+1) if i % 2 == 1]
    denominator = len(I1)
    result = x[0]
    for i in I1:
        result += ((x[i-1] - np.sin(6 * np.pi * x[0] + (i * np.pi / n)))**2 )*(2/(denominator))
    return result

#function f2
def f2_1(x):
    n = len(x)
    I2 = [i for i in range(2, n+1) if i % 2 == 0]
    denominator = len(I2)
    result = 1 - np.sqrt(x[0])
    for i in I2:
        result += ((x[i-1] - np.sin(6 * np.pi * x[0] + (i * np.pi / n)))**2 )*(2/(denominator))
    return result

# taking random 10 values for input in the range given in the question
x1=[]
x1.append(random.uniform(0.001, 1))
for i in range(9):
  x1.append(random.uniform(-1, 1))
print("f1:", f1_1(x1))
print("f2:", f2_1(x1))


f1: 2.213232820817811
f2: 3.384556157104867


**Optimal Solution Procedure for F1**

*Step-2: gradient and hessian find for f1*

In [165]:
def grad_hess_f1_1(x):
  f0=f1_1(x)
  n=len(x)
  h= 10**(-5)
  b=np.zeros(n)
  g=np.zeros(n)
  H=np.zeros((n,n))
  for i in range(0,n):
    x1=x.copy()
    x1[i]=x1[i]+h
    b[i]=f1_1(x1)
    g[i]=(f1_1(x1)-f0)/h
  for i in range(0,n):
    for j in range(0,n):
      x2=x.copy()
      x2[i]=x2[i]+h
      x2[j]=x2[j]+h
      H[i][j]=(f1_1(x2)-b[i]-b[j]+f0)/h**2
  # solver.qp()
  return g,H

In [166]:
g1_1,h1_1 = grad_hess_f1_1(x1)
print(g1_1)
print(h1_1)

[12.75821308  0.          1.6379952   0.          0.12064833  0.
 -0.14896497  0.          0.13511519  0.        ]
[[ 78.27261506   0.           7.73600739   0.          -3.84485332
    0.         -13.95710214   0.         -18.73821986   0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  7.73600739   0.           1.00000008   0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [ -3.84485332   0.           0.           0.           1.00000008
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [-13.95710214   0.           0.           0.           0.
    0.           1.00000452   0.           0.   

*Step-3: Eigen value finding for hessian matrix of f1 and check if all are positive or not if positive find optimal solution else make hessian positive and find optimal solution*

In [167]:
v1_1,u1_1=np.linalg.eig(h1_1)
v1_1

array([85.60710871, -6.33449218,  1.00000313,  1.00000008,  1.00000008,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ])

*Hessian is not positive definite and hence to find optimal solution we have to make it positive definite by following below formula*

Step-4: New Heassian FInding

In [168]:
newH1_1 = h1_1@h1_1 + (0.001-min(v1_1))*np.identity(10, dtype = float)

In [169]:
np.linalg.eig(newH1_1)

(array([7.33491255e+03, 4.64612834e+01, 7.33549844e+00, 7.33549234e+00,
        7.33549234e+00, 6.33549218e+00, 6.33549218e+00, 6.33549218e+00,
        6.33549218e+00, 6.33549218e+00]),
 array([[-9.59284423e-01,  2.82441844e-01, -8.27326687e-08,
         -5.25073162e-17,  6.24045890e-17,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [-8.77116771e-02, -2.97903674e-01, -2.10061450e-01,
          5.16002592e-01, -7.74439565e-01,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.0

*As we can see above for new hessian matrix eigen values are coming out positive and hence we have positive definite hessian matrix and using this we will find optimal solution*

Step-6: FInd Optimal Solution

In [170]:
A1_1=np.vstack((-np.identity(10),np.identity(10)))
lb1_1=[0.001,-1,-1,-1,-1,-1,-1,-1,-1,-1]
ub1_1=[1,1,1,1,1,1,1,1,1,1]
lb1_1 = np.array(lb1_1)
ub1_1 = np.array(ub1_1)
b1_1=np.append(x1-lb1_1,ub1_1-x1)
soln_1= solvers.qp(matrix(newH1_1),matrix(g1_1),matrix(A1_1),matrix(b1_1))
print(np.round_(soln_1['x'],decimals=5),soln_1['primal objective'])
v1_11 = np.round_(soln_1['x'],decimals=5)

     pcost       dcost       gap    pres   dres
 0:  2.7966e-01 -2.8647e+01  3e+01  5e-17  4e-16
 1: -2.0599e-01 -1.4280e+00  1e+00  2e-16  4e-15
 2: -2.8175e-01 -3.2816e-01  5e-02  2e-16  1e-15
 3: -2.8789e-01 -2.9038e-01  2e-03  2e-16  6e-16
 4: -2.8864e-01 -2.8895e-01  3e-04  1e-16  9e-16
 5: -2.8872e-01 -2.8875e-01  4e-05  2e-16  2e-15
 6: -2.8872e-01 -2.8872e-01  2e-06  1e-16  1e-15
 7: -2.8872e-01 -2.8872e-01  2e-08  2e-16  2e-15
Optimal solution found.
[[-0.02077]
 [-0.     ]
 [-0.18327]
 [-0.     ]
 [-0.03634]
 [-0.     ]
 [-0.05192]
 [-0.     ]
 [-0.11538]
 [ 0.     ]] -0.28872108539681524


***Solution Correctness check***

In [171]:
v1_11 = list(flatten(v1_11))
v2_11= list(g1_1)
np.dot(v2_11,v1_11)

-0.5774231554908237

*Now onwards I will be following same steps as above*

**Optimal Solution Procedure for F2**

*Step-2: Gradient and Hessian finding*

In [172]:
def grad_hess_f2_1(x):
  f0=f2_1(x)
  n=len(x)
  h= 10**(-5)
  b=np.zeros(n)
  g=np.zeros(n)
  H=np.zeros((n,n))
  for i in range(0,n):
    x1=x.copy()
    x1[i]=x1[i]+h
    b[i]=f2_1(x1)
    g[i]=(f2_1(x1)-f0)/h
  for i in range(0,n):
    for j in range(0,n):
      x2=x.copy()
      x2[i]=x2[i]+h
      x2[j]=x2[j]+h
      H[i][j]=(f2_1(x2)-b[i]-b[j]+f0)/h**2
  # solver.qp()
  return g,H

In [173]:
g2_1,h2_1 = grad_hess_f2_1(x1)
print(g2_1)
print(h2_1)

[ 5.17517771  0.76888687  0.          1.59227843  0.          1.10589064
  0.          0.61936656  0.         -0.74315433]
[[-5.39008838e+02  1.01352438e+01  0.00000000e+00  1.63656644e+00
   0.00000000e+00 -7.48723306e+00  0.00000000e+00 -1.37511602e+01
   0.00000000e+00 -1.47626089e+01]
 [ 1.01352438e+01  8.00000066e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.63656644e+00  0.00000000e+00  0.00000000e+00  8.00008948e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  4.44089210e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-7.48723306e+00  0.00000000e+00  0.00000

*Step-3: Eigen values find*

In [174]:
v2_1,u2_1=np.linalg.eig(h2_1)
v2_1

array([-540.05992155,    1.85108542,    0.80001091,    0.80000118,
          0.80000007,    0.80000007,    0.        ,    0.        ,
          0.        ,    0.        ])

not positive deifnite matrix

*Step-4: Find transformed hessian and its eigen values*

In [175]:
newH2_1 = h2_1@h2_1 + (0.001-min(v2_1))*np.identity(10, dtype = float)

In [176]:
np.linalg.eig(newH2_1)

(array([292204.77978523,    543.48743878,    540.700939  ,    540.70092344,
           540.70092166,    540.70092166,    540.06092155,    540.06092155,
           540.06092155,    540.06092155]),
 array([[-9.99029735e-01, -4.40407517e-02,  1.18530699e-07,
          3.51267728e-08, -3.42796966e-15, -1.56415552e-15,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 1.87209469e-02, -4.24669370e-01,  1.10795623e-01,
          3.19869125e-01, -8.30067803e-01, -6.92834893e-02,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 3.02292435e-03, -6.85705287e-02,  9.10957775e-01,
         -4.06749159e-01,  1.89747894e-08,  6.69723463e-09,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
   

*All eigen values are positive and so now we have positive definite hessian to find optimal solution*

*Step-5: Optimal solution*

In [177]:
A2_1=np.vstack((-np.identity(10),np.identity(10)))
lb2_1=[0.001,-1,-1,-1,-1,-1,-1,-1,-1,-1]
ub2_1=[1,1,1,1,1,1,1,1,1,1]
lb2_1 = np.array(lb2_1)
ub2_1 = np.array(ub2_1)
b2_1=np.append(x1-lb2_1,ub2_1-x1)
soln2_1= solvers.qp(matrix(newH2_1),matrix(g2_1),matrix(A2_1),matrix(b2_1))
print(np.round_(soln2_1['x'],decimals=5),soln2_1['primal objective'])
v1_12=np.round_(soln2_1['x'],decimals=5)

     pcost       dcost       gap    pres   dres
 0:  9.2610e-03 -3.0330e+01  3e+01  4e-17  3e-16
 1: -4.9405e-03 -3.2050e-01  3e-01  2e-16  2e-16
 2: -5.0610e-03 -8.2536e-03  3e-03  2e-16  2e-16
 3: -5.0611e-03 -5.0930e-03  3e-05  2e-16  5e-16
 4: -5.0611e-03 -5.0614e-03  3e-07  1e-16  6e-16
 5: -5.0611e-03 -5.0611e-03  3e-09  2e-16  3e-16
Optimal solution found.
[[-5.00e-05]
 [-1.60e-03]
 [-0.00e+00]
 [-2.97e-03]
 [ 0.00e+00]
 [-1.91e-03]
 [ 0.00e+00]
 [-9.10e-04]
 [-0.00e+00]
 [ 1.63e-03]] -0.005061054748060722


***Solution Correctness***

In [178]:
v1_12 = list(flatten(v1_12))
v2_12= list(g2_1)
np.dot(v2_12,v1_12)

-0.010105261045008973

# Question-3

*Function Definition*

In [179]:
import numpy as np

def yi_3(i,x):
  n=len(x)
  if(i%2==1):
    return x[i-1]-((0.3* ((x[0]**2)*np.cos((24 * np.pi * x[0])+(4*i*np.pi / n))) + 0.6*x[0])*(np.cos((6 * np.pi * x[0]) + (i* np.pi / n))))
  else:
    return x[i-1]-((0.3* ((x[0]**2)*np.cos((24 * np.pi * x[0])+(4*i*np.pi / n))) + 0.6*x[0])*(np.sin((6 * np.pi * x[0]) + (i* np.pi / n))))


def f1_3(x):
    n = len(x)
    I1 = [i for i in range(2, n+1) if i % 2 == 1]
    denominator = len(I1)
    result = x[0]
    for i in I1:
        result += (yi_3(i,x)**2)*(2/(denominator))
    return result

def f2_3(x):
    n = len(x)
    I2 = [i for i in range(2, n+1) if i % 2 == 0]
    denominator = len(I2)
    result = 1 - np.sqrt(x[0])
    for i in I2:
        result += (yi_3(i,x)**2)*(2/(denominator))
    return result


x3=[]
x3.append(random.uniform(0.001, 1))
for i in range(9):
  x3.append(random.uniform(-1, 1))
print("f1:", f1_3(x3))
print("f2:", f2_3(x3))


f1: 1.4393328820658566
f2: 1.2420404137674013


***F1 Solution Finding***

*Gradient and Hessian Finding*

In [180]:
def grad_hess_f1_3(x):
  f0=f1_3(x)
  n=len(x)
  h= 10**(-5)
  b=np.zeros(n)
  g=np.zeros(n)
  H=np.zeros((n,n))
  for i in range(0,n):
    x1=x.copy()
    x1[i]=x1[i]+h
    b[i]=f1_3(x1)
    g[i]=(f1_3(x1)-f0)/h
  for i in range(0,n):
    for j in range(0,n):
      x2=x.copy()
      x2[i]=x2[i]+h
      x2[j]=x2[j]+h
      H[i][j]=(f1_3(x2)-b[i]-b[j]+f0)/h**2
  # solver.qp()
  return g,H

In [181]:
g1_3,h1_3 = grad_hess_f1_3(x3)
print(g1_3)
print(h1_3)

[ 2.19812926  0.         -0.53326055  0.          0.68097653  0.
 -0.6168184   0.         -0.24393033  0.        ]
[[ 1.22008889e+03  0.00000000e+00 -2.09057216e+00  0.00000000e+00
  -9.12485865e+00  0.00000000e+00 -7.10873138e+00  0.00000000e+00
  -7.83502374e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.09057216e+00  0.00000000e+00  1.00000008e+00  0.00000000e+00
  -4.44089210e-06  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-9.12485865e+00  0.00000000e+00 -4.44089210e-06  0.00000000e+00
   9.99995642e-01  0.00000000e+00 -2.22044605e-06  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 

*Eigen values Finding*

In [182]:
v1_3,u1_3=np.linalg.eig(h1_3)
v1_3

array([1.22025256e+03, 8.36325149e-01, 1.00000328e+00, 9.99999519e-01,
       9.99995613e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00])

not a positive deifinite matrix

*New Hessian*

In [183]:
newH1_3 = h1_3@h1_3 + (0.001-min(v1_3))*np.identity(10, dtype = float)

In [184]:
np.linalg.eig(newH1_3)

(array([1.48901632e+06, 7.00439755e-01, 1.00099123e+00, 1.00099904e+00,
        1.00100657e+00, 1.00000000e-03, 1.00000000e-03, 1.00000000e-03,
        1.00000000e-03, 1.00000000e-03]),
 array([[-9.99932888e-01, -1.15853376e-02,  2.03066965e-07,
         -9.24153857e-08,  2.38047492e-08,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 1.71451911e-03, -1.47993661e-01, -4.46849688e-01,
          4.76813785e-01, -7.42340156e-01,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.0

All eigen values are positive

*Optimal Solution*

In [185]:
A1_3=np.vstack((-np.identity(10),np.identity(10)))
lb1_3=[0.001,-1,-1,-1,-1,-1,-1,-1,-1,-1]
ub1_3=[1,1,1,1,1,1,1,1,1,1]
lb1_3 = np.array(lb1_3)
ub1_3 = np.array(ub1_3)
b1_3=np.append(x3-lb1_3,ub1_3-x3)
soln1_3= solvers.qp(matrix(newH1_3),matrix(g1_3),matrix(A1_3),matrix(b1_3))
print(np.round_(soln1_3['x'],decimals=5),soln1_3['primal objective'])
v1_3=np.round_(soln1_3['x'],decimals=5)

     pcost       dcost       gap    pres   dres
 0: -4.6508e-01 -2.3620e+01  2e+01  5e-17  7e-13
 1: -5.4418e-01 -2.0920e+00  2e+00  2e-16  3e-13
 2: -5.8949e-01 -6.4186e-01  5e-02  2e-16  4e-13
 3: -5.9188e-01 -5.9750e-01  6e-03  2e-16  3e-13
 4: -5.9232e-01 -5.9259e-01  3e-04  2e-16  3e-13
 5: -5.9236e-01 -5.9237e-01  2e-05  2e-16  1e-13
 6: -5.9236e-01 -5.9236e-01  8e-07  1e-16  4e-14
 7: -5.9236e-01 -5.9236e-01  1e-08  1e-16  3e-13
Optimal solution found.
[[ 9.8000e-04]
 [ 0.0000e+00]
 [ 5.3271e-01]
 [ 0.0000e+00]
 [-6.8033e-01]
 [-1.0000e-05]
 [ 6.1617e-01]
 [-8.0000e-05]
 [ 2.4366e-01]
 [-0.0000e+00]] -0.5923572343181047


***Solution Correctness***

In [186]:
v1_3 = list(flatten(v1_3))
v2_3= list(g1_3)
np.dot(v2_3,v1_3)

-1.184708879857571

***F2 Solution Finding***

In [187]:
def grad_hess_f2_3(x):
  f0=f2_3(x)
  n=len(x)
  h= 10**(-5)
  b=np.zeros(n)
  g=np.zeros(n)
  H=np.zeros((n,n))
  for i in range(0,n):
    x1=x.copy()
    x1[i]=x1[i]+h
    b[i]=f2_3(x1)
    g[i]=(f2_3(x1)-f0)/h
  for i in range(0,n):
    for j in range(0,n):
      x2=x.copy()
      x2[i]=x2[i]+h
      x2[j]=x2[j]+h
      H[i][j]=(f2_3(x2)-b[i]-b[j]+f0)/h**2
  # solver.qp()
  return g,H

In [188]:
g2_3,h2_3 = grad_hess_f2_3(x3)
print(g2_3)
print(h2_3)

[-18.65398943   0.10261125   0.           0.13593831   0.
   0.9239708    0.           0.87389968   0.           0.46032055]
[[ 6.46162190e+02  5.68698200e+00  0.00000000e+00  6.26801722e+00
   0.00000000e+00 -1.20169230e+01  0.00000000e+00 -1.67245995e+00
   0.00000000e+00 -7.29988514e+00]
 [ 5.68698200e+00  7.99997846e-01  0.00000000e+00 -2.22044605e-06
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.22044605e-06
   0.00000000e+00  2.22044605e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 6.26801722e+00 -2.22044605e-06  0.00000000e+00  7.99997846e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.22044605e-06
   0.00000000e+00  2.22044605e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.20169230e+01  0.00000000e+00  0.000

*Eigen values Finding for f2*

In [189]:
v2_3,u2_3=np.linalg.eig(h2_3)
v2_3

array([6.46583573e+02, 3.78618592e-01, 7.99994665e-01, 8.00000995e-01,
       8.00003835e-01, 8.00000066e-01, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00])

*not positive definite matrix*

*New hessian calculation*

In [190]:
newH2_3 = h2_3@h2_3 + (0.001-min(v2_3))*np.identity(10, dtype = float)

In [191]:
np.linalg.eig(newH2_3)

(array([4.18070317e+05, 1.44352038e-01, 6.40991463e-01, 6.41006136e-01,
        6.41001593e-01, 6.41000106e-01, 1.00000000e-03, 1.00000000e-03,
        1.00000000e-03, 1.00000000e-03]),
 array([[-9.99673903e-01,  2.55360041e-02,  2.86516942e-07,
          2.20160504e-08,  1.28088280e-07,  6.54086704e-16,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [-8.80345625e-03, -3.44640594e-01,  3.77385230e-01,
         -1.63902134e-01,  4.18909383e-01,  7.32377478e-01,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [-9.70289961e-03, -3.79851724e-01,  3.46565008e-01,
         -1.60507694e-01,  4.98996238e-01, -6.78786599e-01,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.0

*All eigen values are positive*


*Optimal Solution Find*

In [192]:
A2_3=np.vstack((-np.identity(10),np.identity(10)))
lb2_3=[0.001,-1,-1,-1,-1,-1,-1,-1,-1,-1]
ub2_3=[1,1,1,1,1,1,1,1,1,1]
lb2_3 = np.array(lb2_3)
ub2_3 = np.array(ub2_3)
b2_3=np.append(x3-lb2_3,ub2_3-x3)
soln2_3= solvers.qp(matrix(newH2_3),matrix(g2_3),matrix(A2_3),matrix(b2_3))
print(np.round_(soln2_3['x'],decimals=5),soln2_3['primal objective'])
v1_32 = np.round_(soln2_3['x'],decimals=5)

     pcost       dcost       gap    pres   dres
 0: -1.0368e+00 -2.4147e+01  2e+01  4e-17  2e-13
 1: -1.1831e+00 -3.0421e+00  2e+00  2e-16  1e-13
 2: -1.3335e+00 -1.4534e+00  1e-01  1e-16  3e-14
 3: -1.3566e+00 -1.3663e+00  1e-02  1e-16  1e-14
 4: -1.3594e+00 -1.3599e+00  4e-04  1e-16  8e-14
 5: -1.3595e+00 -1.3595e+00  3e-05  1e-16  1e-13
 6: -1.3595e+00 -1.3595e+00  8e-07  1e-16  4e-14
Optimal solution found.
[[-5.20700e-02]
 [ 1.28530e-01]
 [ 5.40000e-04]
 [ 1.06020e-01]
 [-3.05000e-03]
 [-1.82186e+00]
 [ 2.00000e-05]
 [-1.44822e+00]
 [-3.00000e-05]
 [-1.08858e+00]] -1.3594932932967887


***Solution Correctness***

In [193]:
v1_32 = list(flatten(v1_32))
v2_32= list(g2_3)
np.dot(v2_32,v1_32)

-2.4511261516133804

# Question-4

Function definition

In [194]:
import numpy as np

def yi_4(i,x):
  n=len(x)
  return x[i-1] - x[0]**(0.5*(1 + (3*((i-2)/(n-2)))))


def f1_4(x):
    n = len(x)
    I1 = [i for i in range(2, n+1) if i % 2 == 1]
    denominator = len(I1)
    result = x[0]
    y_values = [yi_4(i, x) for i in I1]
    sum_y_squared = sum([y ** 2 for y in y_values])
    cos_multiplication=1
    for i in I1:
      cos_multiplication = cos_multiplication * np.cos((20 * yi_4(i,x) * np.pi)/ np.sqrt(i))
    result = result + (2/denominator)*(4*sum_y_squared - 2*cos_multiplication + 2)
    return result

def f2_4(x):
    n = len(x)
    I2 = [i for i in range(2, n+1) if i % 2 == 0]
    denominator = len(I2)
    result = 1 - np.sqrt(x[0])
    y_values = [yi_4(i, x) for i in I2]
    sum_y_squared = sum([y ** 2 for y in y_values])
    cos_multiplication=1
    for i in I2:
      cos_multiplication = cos_multiplication * np.cos((20 * yi_4(i,x) * np.pi)/ np.sqrt(i))
    result = result + (2/denominator)*(4*sum_y_squared - 2*cos_multiplication + 2)
    return result

# Example usage
x4=[]
x4.append(random.uniform(0.001, 1))
for i in range(9):
  x4.append(random.uniform(-1, 1))
print("f1:", f1_4(x4))
print("f2:", f2_4(x4))


f1: 9.65613792929019
f2: 8.132580569897769


***F1 Solution***

*Gradient and hessian*

In [195]:
def grad_hess_f1_4(x):
  f0=f1_4(x)
  n=len(x)
  h= 10**(-5)
  b=np.zeros(n)
  g=np.zeros(n)
  H=np.zeros((n,n))
  for i in range(0,n):
    x1=x.copy()
    x1[i]=x1[i]+h
    b[i]=f1_4(x1)
    g[i]=(f1_4(x1)-f0)/h
  for i in range(0,n):
    for j in range(0,n):
      x2=x.copy()
      x2[i]=x2[i]+h
      x2[j]=x2[j]+h
      H[i][j]=(f1_4(x2)-b[i]-b[j]+f0)/h**2
  # solver.qp()
  return g,H

In [196]:
g1_4,h1_4 = grad_hess_f1_4(x4)
print(g1_4)
print(h1_4)

[-1.36302355  0.         -6.24061788  0.         10.66977826  0.
 -4.67556627  0.          1.29900568  0.        ]
[[ 1.10746942e+03  0.00000000e+00 -9.10906337e+02  0.00000000e+00
  -5.05946538e+02  0.00000000e+00  3.79805698e+01  0.00000000e+00
   4.12611811e+01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-9.10906337e+02  0.00000000e+00  2.43261589e+01  0.00000000e+00
   8.46041939e+02  0.00000000e+00  3.59612784e+00  0.00000000e+00
   3.77069043e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-5.05946538e+02  0.00000000e+00  8.46041939e+02  0.00000000e+00
   1.60775926e+01  0.00000000e+00 -5.41868594e+01  0.00000000e+00
  -5.68173064e+01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 

*Eigen values*

In [197]:
v1_4,u1_4=np.linalg.eig(h1_4)
v1_4

array([ 2.01520182e+03, -8.87212551e+02,  3.16238712e+01, -2.34729500e-01,
        1.19714485e+01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00])

*not positive definite matrix*

*New hessian*

In [198]:
newH1_4 = h1_4@h1_4 + (0.001-min(v1_4))*np.identity(10, dtype = float)

In [199]:
np.linalg.eig(newH1_4)

(array([4.06192560e+06, 7.88033324e+05, 1.88728278e+03, 8.87268649e+02,
        1.03052913e+03, 8.87213551e+02, 8.87213551e+02, 8.87213551e+02,
        8.87213551e+02, 8.87213551e+02]),
 array([[-0.75011902, -0.19545195, -0.48607773,  0.4017311 , -0.03821729,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.51744921, -0.76340653, -0.2400796 ,  0.30227965, -0.02110876,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.4102338 ,  0.61163769, -0.52941909,  0.41910233, -0.04094175,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.     

*All eigens are positive*

*Optimal Solution*

In [200]:
A1_4=np.vstack((-np.identity(10),np.identity(10)))
lb1_4=[0.001,-1,-1,-1,-1,-1,-1,-1,-1,-1]
ub1_4=[1,1,1,1,1,1,1,1,1,1]
lb1_4 = np.array(lb1_4)
ub1_4 = np.array(ub1_4)
b1_4=np.append(x4-lb1_4,ub1_4-x4)
soln1_4= solvers.qp(matrix(newH1_4),matrix(g1_4),matrix(A1_4),matrix(b1_4))
print(np.round_(soln1_4['x'],decimals=5),soln1_4['primal objective'])
v1_41=np.round_(soln1_4['x'],decimals=5)

     pcost       dcost       gap    pres   dres
 0: -7.5576e-03 -2.8751e+01  3e+01  4e-17  1e-14
 1: -1.5077e-02 -3.0367e-01  3e-01  3e-16  3e-14
 2: -1.5078e-02 -1.7964e-02  3e-03  1e-16  3e-14
 3: -1.5078e-02 -1.5107e-02  3e-05  1e-16  3e-14
 4: -1.5078e-02 -1.5079e-02  3e-07  2e-16  1e-14
 5: -1.5078e-02 -1.5078e-02  3e-09  2e-16  3e-14
Optimal solution found.
[[-0.00138]
 [-0.     ]
 [-0.00072]
 [-0.     ]
 [-0.00151]
 [ 0.     ]
 [ 0.00386]
 [ 0.     ]
 [-0.00178]
 [ 0.     ]] -0.015078244504678925


***Solution Correctness***

In [201]:
v1_41 = list(flatten(v1_41))
v2_41= list(g1_4)
np.dot(v2_41,v1_41)

-0.030097063709987992

***F2 Solution***

*Gradient and Hessian*

In [202]:
def grad_hess_f2_4(x):
  f0=f2_4(x)
  n=len(x)
  h= 10**(-5)
  b=np.zeros(n)
  g=np.zeros(n)
  H=np.zeros((n,n))
  for i in range(0,n):
    x1=x.copy()
    x1[i]=x1[i]+h
    b[i]=f2_4(x1)
    g[i]=(f2_4(x1)-f0)/h
  for i in range(0,n):
    for j in range(0,n):
      x2=x.copy()
      x2[i]=x2[i]+h
      x2[j]=x2[j]+h
      H[i][j]=(f2_4(x2)-b[i]-b[j]+f0)/h**2
  # solver.qp()
  return g,H

In [203]:
g2_4,h2_4 = grad_hess_f2_4(x4)
print(g2_4)
print(h2_4)

[10.35567587 -0.84100555  0.         -0.35570674  0.         -4.07056099
  0.         -5.39096169  0.          1.25985665]
[[-1257.78512938   213.06428621     0.           137.20516279
      0.            68.62453716     0.           183.51999032
      0.           461.79936319]
 [  213.06428621   -27.7253065      0.            18.32228591
      0.             9.05647113     0.            23.89104026
      0.          -172.25756821]
 [    0.             0.             0.             0.
      0.             0.             0.             0.
      0.             0.        ]
 [  137.20516279    18.32228591     0.           -12.26503343
      0.             5.79523984     0.            15.28787763
      0.          -110.22766699]
 [    0.             0.             0.             0.
      0.             0.             0.             0.
      0.             0.        ]
 [   68.62453716     9.05647113     0.             5.79523984
      0.            -7.11146697     0.             7.55660423


*Eigen values*

In [204]:
v2_4,u2_4=np.linalg.eig(h2_4)
v2_4

array([-1.50655092e+03,  2.75241595e+02, -4.59387039e+01,  6.91148398e-01,
       -1.16781103e+01, -2.41874085e+01,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00])

Not positive definite

*FInd new hessian*

In [205]:
newH2_4 = h2_4@h2_4 + (0.001-min(v2_4))*np.identity(10, dtype = float)

In [206]:
np.linalg.eig(newH2_4)

(array([2.27120223e+06, 7.72644874e+04, 3.61691644e+03, 1.50702961e+03,
        1.64293018e+03, 2.09158265e+03, 1.50655192e+03, 1.50655192e+03,
        1.50655192e+03, 1.50655192e+03]),
 array([[-0.91428169,  0.088953  ,  0.11593965,  0.36691686, -0.08941894,
          0.0105177 ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.16544974, -0.41628951,  0.86154413,  0.2168467 , -0.09990104,
         -0.00827248,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.10409344, -0.29494222, -0.26628218,  0.33360915, -0.23828627,
          0.81436603,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
        [ 0.05146255, -0.15269783, -0.08292947,  0.40924184,  0.89423

*All eigen values are positive and hence find optimal solution*

In [207]:
A2_4=np.vstack((-np.identity(10),np.identity(10)))
lb2_4=[0.001,-1,-1,-1,-1,-1,-1,-1,-1,-1]
ub2_4=[1,1,1,1,1,1,1,1,1,1]
lb2_4 = np.array(lb2_4)
ub2_4 = np.array(ub2_4)
b2_4=np.append(x4-lb2_4,ub2_4-x4)
soln2_4= solvers.qp(matrix(newH2_4),matrix(g2_4),matrix(A2_4),matrix(b2_4))
print(np.round_(soln2_4['x'],decimals=5),soln2_4['primal objective'])
v1_42=np.round_(soln2_4['x'],decimals=5)

     pcost       dcost       gap    pres   dres
 0: -2.2034e-03 -2.8772e+01  3e+01  5e-17  2e-14
 1: -5.9809e-03 -2.9403e-01  3e-01  2e-16  8e-15
 2: -5.9813e-03 -8.8618e-03  3e-03  2e-16  5e-15
 3: -5.9813e-03 -6.0101e-03  3e-05  1e-16  2e-15
 4: -5.9813e-03 -5.9816e-03  3e-07  2e-16  4e-15
 5: -5.9813e-03 -5.9813e-03  3e-09  1e-16  1e-14
Optimal solution found.
[[-0.00024]
 [-0.00086]
 [ 0.     ]
 [-0.00127]
 [ 0.     ]
 [ 0.00162]
 [ 0.     ]
 [ 0.00066]
 [-0.     ]
 [-0.00036]] -0.0059813083999579585


**Solution Correctness**

In [208]:
v1_42 = list(flatten(v1_42))
v2_42= list(g2_4)
np.dot(v2_42,v1_42)

-0.011916241792194526